dist: bionic

sudo: required

language: cpp
services:
  - docker

env:
  global:
    - RELEASE_BRANCH="main"

script:
  - bash ./deploy.sh

after_success:
  - mkdir result

  # result
  - mv ./*AppImage ./result/
  - mv ./*zsync ./result/

  # md5sum tool
  - wget -c https://github.com/ferion11/libsutil/releases/download/md5sum_util_v0.1/md5sum_util.sh
  - bash md5sum_util.sh result

  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh

  - |- # publish
    if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
      export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/main/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
      echo 'Removing old continuous release first...'
      curl -XDELETE --header "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/ferion11/emerge_AppImage/releases/continuous"
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/main/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    else
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/main/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always