#!/bin/bash -e
HERE_RO="$(dirname "$(readlink -f "${0}")")"
HERE_RW="${HERE_RO}_rw"
HERE_UPPER="${HERE_RO}_upper"
HERE_TMP="${HERE_RO}_tmp"

if [ "$(id -u)" != 0 ]; then
	echo "* This AppImage need to be run with root!"
	exit 1
fi
#=================================================
have_dep() {
	command -v "$1" >/dev/null 2>&1
}
check_commands() {
	for cmd in "$@"; do
		if ! have_dep "${cmd}"; then
			echo "* Your system does not have the command: ${cmd}. Please install it!"
			exit 1
		fi
	done
}
check_commands chroot mount umount unionfs

#TODO!!!: check kernel support for mount squashfs, OverlayFS, chroot...
# https://wiki.gentoo.org/wiki/OverlayFS
#=================================================
function cleanup {
	umount -f "${HERE_RW}/lib/modules"
	umount -f "${HERE_RW}/usr/src/linux"
	umount -f "${HERE_RW}/dev/pts"
	umount -f "${HERE_RW}/run"

	umount -f "${HERE_RW}/var/log"
	umount -f "${HERE_RW}/var/cache/binpkgs"
	umount -f "${HERE_RW}/var/cache/distfiles"
	umount -f "${HERE_RW}/var/db/repos"

	umount -f "${HERE_RW}/mnt/host"

	umount -f "${HERE_RW}/proc"
	umount -f "${HERE_RW}/sys"
	umount -f "${HERE_RW}/dev"

	umount -f "${HERE_RW}"
	rm -rf "${HERE_RW}"
	rm -rf "${HERE_UPPER}"
	rm -rf "${HERE_TMP}"
}
#-------
trap cleanup EXIT
#-------
mkdir -p "${HERE_TMP}"
mkdir -p "${HERE_UPPER}"
mkdir -p "${HERE_RW}"
#=================================================
mount -t overlay overlay -o lowerdir="${HERE_RO}",upperdir="${HERE_UPPER}",workdir="${HERE_TMP}" "${HERE_RW}"

mount --rbind /dev "${HERE_RW}/dev"
mount --rbind /sys "${HERE_RW}/sys"
mount -t proc none "${HERE_RW}/proc"

mount --rbind / "${HERE_RW}/mnt/host"

mount -o bind,rw /var/db/repos "${HERE_RW}/var/db/repos"
mount -o bind,rw /var/cache/distfiles "${HERE_RW}/var/cache/distfiles"
mount -o bind,rw /var/cache/binpkgs "${HERE_RW}/var/cache/binpkgs"
mount -o bind,rw /var/log "${HERE_RW}/var/log"

mount -t tmpfs -o nosuid,nodev,noexec,mode=755 none "${HERE_RW}/run"
mount -o bind,rw /dev/pts "${HERE_RW}/dev/pts"
mount -o bind,rw /usr/src/linux "${HERE_RW}/usr/src/linux"
mount -o bind,rw /lib/modules "${HERE_RW}/lib/modules"
#=================================================
chroot "${HERE_RW}" ./emerge.sh $@
#=================================================
exit 0
