#!/bin/bash -e
HERE="$(dirname "$(readlink -f "${0}")")"

if [ "$(id -u)" != 0 ]; then
	echo "* This AppImage need to be run with root!"
	exit 1
fi
#=================================================
have_dep() {
	command -v "$1" >/dev/null 2>&1
}
check_commands() {
	for cmd in "$@"; do
		if have_dep "${cmd}"; then
			echo "* command ${cmd} is installed!"
		else
			echo "* Your system does not have the command: ${cmd}. Please install it!"
			exit 1
		fi
	done
}
check_commands mount umount chroot
#=================================================
function cleanup {
	umount -f ${HERE}/usr/tmp
	umount -f ${HERE}/var/tmp
	umount -f ${HERE}/tmp
	umount -f ${HERE}/var/log
	umount -f ${HERE}/var/cache/binpkgs
	umount -f ${HERE}/var/cache/distfiles
	umount -f ${HERE}/var/db/repos

	umount -f ${HERE}/mnt/host

	umount -f ${HERE}/sys
	umount -f ${HERE}/proc
	umount -f ${HERE}/dev
}
#-------
trap cleanup EXIT
#=================================================
mount --rbind /dev ${HERE}/dev
mount --rbind /proc ${HERE}/proc
mount --rbind /sys ${HERE}/sys

mount --rbind / ${HERE}/mnt/host

mount --rbind /var/db/repos ${HERE}/var/db/repos
mount --rbind /var/cache/distfiles ${HERE}/var/cache/distfiles
mount --rbind /var/cache/binpkgs ${HERE}/var/cache/binpkgs
mount --rbind /var/log ${HERE}/var/log
mount --rbind /tmp ${HERE}/tmp
mount --rbind /var/tmp ${HERE}/var/tmp
mount --rbind /usr/tmp ${HERE}/usr/tmp
#=================================================
chroot ${HERE} ./emerge.sh $@
#=================================================
exit 0
